Boscop/web-view

Cargo.toml, build.rs, webview-c/lib.c
This makes the build script handle BSDs. I still can't compile on FreeBSD as I'm getting the same issue finding the header file that [/u/LousyBegger reported on Reddit](https://www.reddit.com/r/rust/comments/7rwf5k/start_rust2018_by_making_your_first_rust_desktop/dt07xtz/) but this gets it a little closer.
=> Add BSD support (and fix building on Linux)

Cargo.toml, build.rs, webview-c/lib.c
This fixes macos compile. I'm not sure why you chose to use cpp instead of c, but since it uses no C++ features it seems redundant to use C++ to me. If you have bigger plans and want C++, you can just take the compile flags and commit those.
I switched to cc crate from gcc, because it was deprecated for cc.
=> fix macos, use c instead of cpp

.travis.yml
Run builds on Linux and macOS against the stable, beta and nightly compilers, and don't let failing nightly compiler builds fail the overall build.
I've removed the osx_image key because xcode8.3 is the default value.
This is for #4. Hopefully it'll pass.
=> Fix Travis build matrix

examples/timer.rs
Between the declaration of `userdata` variable in `main()` and its first use, there are closures that contain different `userdata` variables. I recommend renaming the variable to make it more clear that it is only used once, and that it is an initial value. Other examples don't have this problem.
=> Make timer example less confusing by renaming one of userdata variables

build.rs
Although I think this is necessary for it work for MinGW, it doesn't *seem* to break MSVC builds, either.
```sh
cc main.c -DWEBVIEW_WINAPI=1 -lole32 -lcomctl32 -loleaut32 -luuid -mwindows -o webview-example.exe
```
This might fix #12.
=> Link to appropriate Windows libraries.

examples/todo.rs, src/lib.rs, webview-sys/lib.rs
This adds support for `webview_set_color` added in zserge/webview#73 which allows you to set the window's background color.
=> Add support for webview_set_color and use it in todo example.

src/lib.rs, webview-sys/lib.rs
This fixes crashes on 32bit Windows (reported in #3)
=> Use C calling convention for callbacks

webview-sys/build.rs
MacOS 10.15 enables objc_msgSend type checking by default. Every call to objc_msgSend would require a cast. This disables the type checking.
```
cargo:warning=In file included from webview.c:2:
cargo:warning=webview/webview.h:1755:43: error: too many arguments to function call, expected 0, have 2
cargo:warning=                   id path = objc_msgSend(url, sel_registerName("path"));
cargo:warning=                             ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
cargo:warning=OBJC_EXPORT void
cargo:warning=^
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro …
```
=> fix "too many arguments to function call" on Catalina

Cargo.toml, README.md, examples/README.md, webview-sys/Cargo.toml, webview-sys/build.rs, webview-sys/webview_edge.cc, webview-sys/webview_edge.h
Adds edge html backend taken from [zserge/webview](https://github.com/zserge/webview/tree/webview-x) (webview-x branch).
The old backends remain the same, I just took the one implementation and copied here, created c function wrappers compatible with original webview, fixed some bugs that caused crashes and implemented navigation to static base64 encoded content (previously you could only navigate to url).
Some functions are not yet implemented so not everything works.
Things that work:
- Calling into javascript from rust with eval
- All examples except ~~`todo`~~ and `actix` - todo example now works
Things that do not work:
- ~~Calling Rust invoke_handler from webview's javascript~~ - works now
- ~~Fullscreen mode~~ - works now
- ~~Dialogs~~ - works now
- ~~Css injection~~ - works now
- …
=> Implement EdgeHTML windows backend

webview-sys/webview_gtk.c
When attempting to make use of webgl with the webkit/gtk backend, the feature is unavailable.
This enables webgl (WebGL, not WebGL2), and hardware acceleration for canvas.
It may be desirable to move this behind a setting for the `WebViewBuilder`, but decided against it because I am unsure whether WebGL is enabled and available on the other backends.
=> Enable webgl and hardware acceleration for webview_gtk canvas

webview-sys/webview_edge.cpp
Addresses #74 
With this change, the processes `WWAHost.exe` and `Win32WebViewHost.exe` are properly ended when `WebView::terminate()` is used to close the web view.
Only one instance of the `RuntimeBroker.exe` process will remain open if multiple web views are opened and closed.
=> Fix Edge backend process leak

webview-sys/webview_mshtml.c
I haven't looked at the result of the change, the method body may need attention. I am testing this out on some systems and wanted a windows `.exe` without the pain of actually developing on a windows box.
Compile error observed when cross compiling with `cross build --target=x86_64-pc-windows-gnu --release`:
```
webview_mshtml.c: In function 'Site_QueryInterface':
webview_mshtml.c:254:0: note: -Wmisleading-indentation is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
return S_OK;
webview_mshtml.c: At top level:
webview_mshtml.c:1237:0: error: conflicting types for 'webview_exit'
WEBVIEW_API void webview_exit(struct mshtml_webview *w) {
In file included from webview_mshtml.c:1:0:
webview.h:42:18: note: previous declaration of …
```
=> Fixed outdated parameter types found while cross compiling to windows

webview-sys/build.rs, webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
Added missing linked libraries to edge backend.
I also kept the pragmas, if someone want to build the backends separately, so they do not have to supply link library flags to msvc.
Fixes #89
=> Fix linked libraries

webview-sys/webview.h, webview-sys/webview_edge.cpp
- moved functions webview_js_encode and webview_inject_css into webview.h
I have tested it on Windows 10 and Linux.
=> fix for issue #93

webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
Passing strings by value and statements such as `str = str + "foo"` create lots of needless string copies, which means lots of needless allocations. Same with `substr` and `c_str` (in some cases). Also fixed a memory leak (return before free) in the mshtml code.
Using strings this way is a big red flag to experienced C++ devs, because if you get the basics wrong you'll probably end up with at best a slow program and at worst some hard to track down undefined behavior. I'm aware this is a fork from an unmaintained library so I wanted to call attention to the code quality here because I love the potential of this project (came here from tauri) and hope that the C and C++ code will be treated carefully in the future as it's very messy and hard to follow.
=> Clean up usage of std::string in webview_edge.cpp

webview-sys/webview_mshtml.c
When creating the registry key, existing code is using `RegCreateKeyW` with an ASCII literal, and when computing the program name using `strlen` and `'\\'` with a `wchar_t` string.
This PR changes relevant code to always explicitly use `wchar_t`, `...W` APIs and `L"..."` or `L'..'` literals.
Fix #106.
P.S. I think there are maybe more issues like this, which can be caught by the C compiler. Maybe we should run the C/C++ compiler manually to see and fix warnings. If we only use `build.rs` and `cc` these warnings are never shown.
=> mshtml: fix setting registry key to disable compatibility mode

README.md
Thanks to @sopium the root cause of issue #96 has been identified. As
such the `README.md` file has been updated to highlight the fact that
the bug exists in the internal Edge WebView implementation (rather than
this library's abstraction).
=> Update documentation to clarify known issues

examples/dialog.rs, examples/graceful_exit.rs, examples/graceful_exit/index.html, examples/timer.rs, src/error.rs, src/lib.rs, webview-sys/lib.rs, webview-sys/webview.h, webview-sys/webview_cocoa.c, webview-sys/webview_edge.cpp, webview-sys/webview_gtk.c
This is one possible option for allowing the invoke_handler to gracefully request a shutdown of the window to address #105.
This was the quickest thing I could think of but I am not sure it is really the best approach. One thing that might be better would be to put a new flag on `UserData` to indicate that `run` should exit
=> Allow for graceful Exit

webview-sys/webview.h, webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
Previously `sscanf` is used in decoding the url-encoded html document.
But `sscanf` is quite expensive. Loading a larger document (~800KiB) has
a noticeable delay.
And mshtml is giving the third argument to `sscanf` a `char*` when it
should be an `int*`. It is very problematic.
This commit replaces them with our own hex decoding function.
=> mshtml, edge: speed up `Content::Html`

src/lib.rs
I made a mistake using `derive(Clone)` on `Handle` in #120, the derived instance has an unnecessary `T: Clone` bound: https://docs.rs/web-view/0.6.0/web_view/struct.Handle.html#impl-Clone
Change to manual implementation.
=> Implement clone manually

src/lib.rs
On Ubuntu 16.04 with libwebkit2gtk-4.0, I had a deadlock during the shutdown (reproducible with any example).
For what I understand when leaving the function `user_data` is destroyed first, then `_lock` is destroyed but the underlying `RWLock<>` has already been destroyed (it is part of `UserData<>`). As a result it deadlocks.
=> Fix deadlock during shutdown

examples/frameless.rs, src/lib.rs, webview-sys/lib.rs, webview-sys/webview.h, webview-sys/webview_cocoa.c, webview-sys/webview_edge.cpp, webview-sys/webview_gtk.c, webview-sys/webview_mshtml.c
This is a first pass at allowing a frame-less window (#82). One thing I noticed is that the options for resizeable and frame-less will ultimately clash as frame-less cannot be resizable. 
If you'd prefer I can add an enum for `DisplayStyle` with two variants `Resizable` and `Frameless` to clarify that these cannot both exist at the same time.
=> Frameless window

webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
#117 is a bit inactive so I finished it myself.
Close #99.
It works but for mshtml I could not figure out how to make the browser correctly handle DPI changes. So mshtml uses *system DPI awareness* for now.
(FWIW, using the WebBrowser control in WPF, and `FEATURE_96DPI_PIXEL`, it correctly handles DPI changes. So it should be possible.)
=> windows: enable DPI awareness

README.md
Github Flavored Markdown uses indentation for code (See: https://github.github.com/gfm/#indented-code-blocks). Thus, you have to either use code tags or indentation, but not both.
=> Fixed the style of the output in the README

webview-sys/webview_edge.cpp
according to the example [here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/collections)
also mentioned in [this issue](https://github.com/Microsoft/xlang/issues/291#issuecomment-480666097) 
Should fix #189
=> add new header to fix build error on newer SDKs

src/lib.rs, webview-sys/gtk.rs, webview-sys/lib.rs, webview-sys/webview.h, webview-sys/webview_cocoa.c, webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
I am unsure of how to achieve this on cocoa.
This should allow one to call webview.set_maximized(bool) to maximize the window.
=> Implement maximize method, for frameless windows, for edge and gtk backend.

README.md, src/lib.rs, webview-sys/gtk.rs, webview-sys/lib.rs, webview-sys/webview.h, webview-sys/webview_cocoa.c, webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
part of #199 
This should allow the one to call webview.set_minimized(), to set the window state to minimized.
The window can then be restored by normal means.
=> Implement minimize method, for frameless windows, for edge and gtk backend.

src/lib.rs, webview-sys/gtk.rs, webview-sys/lib.rs, webview-sys/webview.h, webview-sys/webview_cocoa.c, webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
Added a way to show or hide the window. I've tested in Edge, MSHTML, Cocoa, GTK and found no problems.
Having the ability to hide the window is useful in Edge because it has a white background when the window first appears, and `set_color()` has no effect. After the page load, I show the window, bypassing a horrible experience of seeing the page load.
=> Window visibility control.

webview-sys/Cargo.toml
Hello,
One of my projects needed `glib = "^0.10"` so I upgraded the dependencies of `webview-sys`, and here's a PR if that's of any use to you.
I tested all the examples and they work fine on my Ubuntu 20.04.
If there are other tests I can do to make sure I didn't break anything, please let me know!
=> Upgrade dependencies

webview-sys/webview_cocoa.c
On macOS, pressing Cmd+Q or using the "Quit" menu item will terminate the application. In other words, `WebView::run()` never returns, preventing the application from performing any cleanup or other tasks (e.g. saving the user data).
This patch switches the "Quit" menu item to send the `close` message instead of `terminate:`. But only if there is a close button on the window. The `terminate:` message will still be used on frameless windows. (I haven't found a way to gracefully close them without terminating the app.)
Using the `close` message allows `WebView::run()` to return, and the application can continue running in the background or open a new window if it wants to.
=> macOS: Allow graceful close with Cmd+Q

src/lib.rs
`WebView::{step,run}`, as they stand, invoke `webview_loop` in a non-blocking manner. In the case where there is no work to be done, this turns invocations of `WebView::{step,run}` into busy-wait operations, with the corresponding high CPU usage. Setting `blocking` to true, as this pull request does, should reduce CPU use.
I've tested this PR with the **minimal**, **pageload**, **timer**, and **todo** [examples](https://github.com/Boscop/web-view/tree/master/examples), as well as my work-in-progress [gradient-tool](https://github.com/zec/gradient-tool), on Linux (so using GTK/WebKit). Without the change in this PR, once the application has completed loading, it uses over 99% CPU on idle (no user interaction) per `top`. With the change, idle CPU use is under 1% with application …
=> Set blocking in use of webview_loop to avoid busy-waiting

webview-sys/gtk.rs
With the latest `master`, I can reproduce issue #206 ([original example](https://github.com/kellpossible/web-view-test/tree/2a939c84ac5c2f0ed32fd43b50cb0f1714b159af) and [my take on it](https://github.com/zec/webview-minimal-reproductions/tree/5d99c7f24b99ada5522cf8b6b2d24e8faea5a683/issue206)): when using the GTK/WebKit binding, calling WebView::exit() does not actually close the `web-view`-generated window. This PR fixes that by ensuring the GtkWindow is closed upon a call to exit().
=> GTK: close the window on WebView::exit() (fix for #206)

Cargo.toml, webview-sys/Cargo.toml
It appears that sometimes the contents of the `Cargo.lock` file in uploaded `web-view` crates cause Rustdoc compilation to fail. As libraries generally shouldn't have `Cargo.lock` files except for local development [[1]](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries), this adds `Cargo.lock` to the file excludes in `Cargo.toml`.
This should fix issue #257.
=> Exclude Cargo.lock from crates uploaded to, e.g., crates.io

src/lib.rs, webview-sys/gtk.rs, webview-sys/lib.rs, webview-sys/webview.h, webview-sys/webview_cocoa.c, webview-sys/webview_edge.cpp, webview-sys/webview_mshtml.c
This new feature allows the user to hide the window instead of closing it. Later, the user can call `set_visible(true)` to restore the window.
To use this feature, the user must call `hide_instead_of_close(true)` when building the `WebView` object.
This feature works well in applications with a tray bar icon. The user can later restore the window by clicking on the application icon, bypassing all the loading necessary to restore the interface otherwise.
=> Hide window instead of closing.

README.md
Tauri now consumes its very own windowing crate [TAO](https://github.com/tauri-apps/tao) and a 100% based rust webview crate [WRY](https://github.com/tauri-apps/wry). Very soon we will support iOS, pureOS, and Android - and we are very close to having a webdriver.io compliant tauri-driver for running e2e tests in the webview.
However, we are primarily removing ourselves from this list because there is a wild rumor circulating that Tauri requires MSHTML, and this is absolutely no longer true.
=> Remove Tauri From Showcase

webview-sys/webview_cocoa.c
I'm not entirely sure what caused this, but I assume it must be a newer C compiler on my end due to an Xcode update or something. `web-view` failed to compile with this error:
```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "webview.h" "-Wall" "-Wextra" "-x" "objective-c" "-std=c11" "-w" "-DDEBUG" "-o" "/Users/realpassy/fbsource/xplat/sonar/facebook/flipper-launcher/target/debug/build/webview-sys-92f7fba9394d5e99/out/webview_cocoa.o" "-c" "webview_cocoa.c"
cargo:warning=webview_cocoa.c:59:6: error: call to undeclared function 'webview_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
cargo:warning=        if (webview_init(wv) != 0) {
cargo:warning= …
```
=> [cocoa] Fix uninitialized webview_init error
